apiVersion: v1
kind: Service
metadata:
  name: api-feed
  labels:
    app: api-feed

spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-feed
  sessionAffinity: None
  type: ClusterIP