apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bams
  region: us-east-1

#vpc:
#  subnets:
#    private:
#      us-east-1a: { id: subnet-0f76a21608d20c424 }
#      us-east-1b: { id: subnet-039f7275dd42949b3 }
#      us-east-1c: { id: subnet-02e5c9125a39d14a4 }

nodeGroups:
  - name: bams-node
    instanceType: t3.micro
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      publicKeyName: bams_udacity
      allow: true