apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer